#:schema node_modules/wrangler/config-schema.json
name = "sublink"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "e38b937c32ea4f8e818fda6da936d07e" }
]

[assets]
directory = "./public"
